name: Spellchecking

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    name: node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-versions }}

      - name: Install dependencies
        run: npm ci

      - name: Run spellcheck
        run: npm run spellcheck
